version: '3.8'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carrental-database
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - carrental-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: carrental-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=database,1433;Database=CarRentalDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true
    depends_on:
      - database
    networks:
      - carrental-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: carrental-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - carrental-network

volumes:
  mssql_data:

networks:
  carrental-network:
    driver: bridge